channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.0.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.11.1
name: mlflow-env
